### ISSUE TITLE
Sam's Thesis Meeting | Nov 7, 2023

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#10]
Sorry for the lateness! This is my proposed agenda for tomorrow (likely to be filled in more later):

1. ~~Refined theories version of Projectile?~~
2. How to best organize [testing summary document](https://github.com/samm82/TestGen-Thesis/blob/main/Testing%20Requirements%20Summary.xlsx)
   a. Does it make sense to have subcategories?
   b. Appropriate level of detail?
   c. Sufficient "citations" (at least for now?)
3. Assumptions for unit testing in [testing summary document](https://github.com/samm82/TestGen-Thesis/blob/main/Testing%20Requirements%20Summary.xlsx)
4. QTODOs from [notes document](https://github.com/samm82/TestGen-Thesis/blob/main/notes.pdf)
   a. Big bang testing with Drasil (Q2)
5. Difference between MT and PBT

**NOTE:** @JacquesCarette may be a bit late, in which case we'll start with bullet point 1

**Comment by smiths** [comment]
Sounds good @samm82, except tomorrow is Nov 7, not 10.  :smile:

For your "Testing Requirements Summary" for "Unit Testing" you have an assumption that the system has multiple modules.  Is this assumption necessary?  Even if there is just one module, you can still test it.  I agree that you need multiple modules for integration testing, but for unit testing I don't think you require multiple modules.  For the assumptions for unit testing you could list "availability of a test oracle".  You can't do unit testing without knowing the expected outputs for the sample inputs.

**Comment by samm82** [comment]
I think the issue number psyched me out 😅

Agreed with both your points; added to the agenda in case we want to discuss this in more depth (especially considering the role of oracles in this table)

**Comment by samm82** [comment]
Below is an overview of what we discussed. My main next step is to look for a knowledge graph/complete summary of testing; this will require an investigation of its correctness and completeness and may require some further work.

@smiths Is a discussion about the refined theories version of Projectile something that should be added to subsequent agendas, or just a topic used to fill time for this specific meeting?

---

**Required Assets:** We identified the following missing required asset columns: subject (what is being tested), harness (how the test is run), checking method, and assumptions/guards. Some of this information exists elsewhere in the document, but needs to be reorganized. It is also important to use clear, unambiguous terminology (e.g., "function" implies it has no side effects). _Note here that user involvement in acceptance testing should likely be a checking method._ 

**Splitting Cells:** Our goal should be to only have one entry in each cell. There are multiple ways to start this process, although it should likely wait until the table is more complete and more patterns emerge:
- areas of confidence indicate where a testing approach could be divided more finely
- the approach column could/should be split in the same way that the category column gets split into approaches
- turn the inputs column into multiple columns, one for each input type, with a binary indicator of whether or not a given testing approach requires each one

**Miscellaneous:**
- We should record the "story" of how categories emerge (especially if they're different than in the literature)
- Big O notation could be used as a test of performance (something to be investigated further)
- For completeness, we might want to include rubber duck testing 😂🦆

**Comment by smiths** [comment]
Nice summary @samm82.  When you are looking for literature summarizing the state of practice for testing, knowledge graph probably isn't the strongest keyword to search for.  Phrases like ontology, taxonomy, and state of the practice, might help in your search.

The refined theories version of projectile is something that I'd like to talk to you about, but it isn't pressing.  We don't need it on the agenda for upcoming meetings.  However, if there is a meeting where Jacques misses part of the meeting, I can fill you in on what I'm doing in my spare time.  :smile:  Once it is done, I'll put it on the agenda for one of our Drasil research group meetings.  We've suspended our group meeting momentarily, but we'll reboot it in the future.

**Comment by JacquesCarette** [comment]
I'll close this issue, as this is a meeting that is now done.
