### ISSUE TITLE
Use `\citep{}`?

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#106]
What did you mean by "Use `\citep{}`" in the below comment? I currently use `\citep` here (see code snippet below). The alternative would be `\citet`, which would result in "For example, ISO/IEC and IEEE (2017) provide the following…"; is that what you mean?

![image](https://github.com/user-attachments/assets/5681e93f-5fe8-4aa9-81f4-137f55c2c2e8)

https://github.com/samm82/TestGen-Thesis/blob/d3fddda905c460980c78e58e470d38bb86e6d579/chapters/01_intro.tex#L30-L33

**Comment by smiths** [comment]
I meant to say use `\citet{}`.  :smile:
