### ISSUE TITLE
Error Seeding vs. Fault Injection Testing

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#108]
@smiths gave the following feedback on this portion of my Scope section (which has since been moved to a V&V of Other Artifacts subsection):
![image](https://github.com/user-attachments/assets/7f53cb4f-5a05-4eef-9b8b-2b06be0f8fc0)

In my mind, while these are similar, they seem to encapsulate different test approaches. Error seeding tests the code by estimating how many bugs remain, while fault injection testing tests the code by seeing how it can detect and recover from faults as a subset of robustness testing. Are these distinct enough to mitigate this confusion, or should this be investigated further, potentially as a discrepancy?

_As a side note, the use of "monitor[]" indicates that text has been omitted from the end of "monitor"; it was originally "monitoring". I seem to recall this came up during my paper review, and I'm pretty sure this is "standard" notation to use. Is it OK if I continue to use it?_

**Comment by smiths** [comment]
@samm82 your explanation makes sense.  The two techniques do the same thing (inject faults), but with different goals (estimate the number of bugs versus testing for robustness).  You should keep both, but I think you should also anticipate that other readers will be like me and not immediately see the difference.  I suggest you add some text to explain to the reader the difference between these two testing approaches.

The use of `[]` seems fine.  I do think we talked about it before.  I just forgot.  :smile:  I suggest that you try to limit your use of direct verbatim quotes to when they are necessary.  I'm probably not the only person that will be confused by the extra notation.  :smile:  If you put the text in your own words, still with the citation, you are fine.   You only really need direct quotes when you are making a point that relies on the specific words that were used in the original.

**Comment by samm82** [comment]
Agreed on your first point. I've been taught that using direct quotes is preferable to paraphrasing since it allows you to benefit from the "authority" of the original source. I should keep in mind to not do this at the expense of clarity, especially when the "authority" of the original sources is in question from this work! 😅

**Comment by smiths** [comment]
Direct quotes don't seem to be in fashion for engineering/science writing.  They are used extensively in the humanities but less so in our kind of work.  You can still use direct quotes, but if you aren't drawing attention to specific words in the original source, an indirect paraphrasing should be fine.

**Comment by samm82** [comment]
Good to know! 😁
