### ISSUE TITLE
Sam's Thesis Meeting | Nov 14, 2023

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#11]
Since I'm feeling sick, I'll attend virtually if that's alright. With the combination of sickness and TA duties, I didn't make a whole lot of progress: I started some of the rearranging of my [testing summary document](https://github.com/samm82/TestGen-Thesis/blob/main/Testing%20Requirements%20Summary.xlsx) from our meeting last week and added some (not all) rows for black-box testing. Some specific questions I had:

1. Am I understanding "test harness" correctly? Any obvious things I'm missing?
2. Granularity of Checking Method
3. Is "Equivalence Partitioning/Classing" a method for testing software, for testing tests, or a testing heuristic? I think it's the third: it doesn't specify a specific way to test software (although it is related to (Sub-)Boundary Testing, etc.) or the test suite (although it is related to Fault Seeding and Mutation Testing), but it provides a good rule of thumb to use when developing tests.
4. Related to 2. above, how should "extra" information like Equivalence Partitioning/Classing (depending on what we decide) and Test Oracles be captured? I had suggested putting Test Oracles in its own page of the document last meeting, which I'm still thinking of doing, but may also add a general "Testing Heuristics" sheet as well in case more of these come up.
5. Any prior knowledge of "Coverage-Based Testing"? (Note that that I haven't really looked into it yet.)

**Comment by samm82** [comment]
The main takeaway from this meeting was that I should prioritize finding any existing classification(s) of software testing built up systematically from examples to avoid potentially doing a lot of redundant work. This may be done in part by looking at how testing frameworks (e.g., JUnit, pytest, QuickCheck) categorize their tests (which will come with the added benefit of having many examples of how these tests are used/built).

As for my summary document, there are some improvements to be made:

1. **Definitions:** terms should be defined unambiguously
a. A definition of "test harness" (perhaps contrasted to "test framework") would be helpful.
b. The literature seems to use "unit testing" to refer to "module testing"; if there's not a term already to refer to "function testing", we might need to come up with one.
2. **Checking Method:** this should be more finely grained (e.g., equality, equivalence, approximation like floating-point errors)
3. **Test Oracles:** this info should be reorganized:
a. Probably makes sense for these to go in a different sheet in the spreadsheet.
b. We should add a column for "is a test oracle necessary?"
4. We should add information on where tests come from (I think some of this information is currently in the Inputs column)

**Comment by JacquesCarette** [comment]
I had never seen ISTQB before just now. They do seem 'real', and the glossary seemed reasonable enough. And yet.

If we can ascertain that these are serious people, then I'm happy enough to go with their definitions. The ones you give above do make sense.
