### ISSUE TITLE
Round Two of Intro/Scope Review

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#110]
I've addressed all of @smiths's review on these first two chapters! For the next phase of review, would it make more sense for @smiths to re-review to see if everything's been addressed (since there are a bunch), or for @JacquesCarette to review these sections next and I assign the review of the next chapter (Methodology) to @smiths once it's ready? I'm pretty sure the second is better but thought I'd double check. 😅

# Lingering Minor Questions

1. In the following portion, I have quotes around "complete" that function as air quotes; we want a complete taxonomy, but realistically, this is infeasible. This is also why I don't include "incomplete" as one of the disqualifications of the existing taxonomies, since it is an unrealistic expectation. Should I elaborate on this rationale, or just explicitly state that we are looking for a complete one (possibly also saying that this is naive/unreasonable to do)?
   ![complete quote](https://github.com/user-attachments/assets/5f44f401-6c43-413d-a010-49e348848353)
2. When referencing subsections in an intro blurb, it seems that it is preferred to use "Title (Section <linked number>)" as opposed to "<linked Title>" (see the first image). However, for longer blurbs, I feel like this could be quite cluttered (see second image). Are these cases where the linked title approach is OK, or should I always be explicitly referencing section numbers?   
![use section numbers](https://github.com/user-attachments/assets/3c1c5c12-d3c5-4372-8b6f-ed9b3ac21ff1)
![section intro that could be cluttered](https://github.com/user-attachments/assets/70c1d2b6-7594-489c-8e28-db05d8c31e2f)

**Comment by smiths** [comment]
I think @JacquesCarette should review the updated chapters that I previously reviewed.  You can assign me to review the new material.

The reader won't  know what you are implying by the quotes around "complete."  I don't think it is unrealistic for the community to aim for a complete taxonomy.  @samm82 shouldn't aim for a complete taxonomy, but that should be the eventual goal for the community.  @samm82 your thesis is helping toward that goal of eventually achieving a complete taxonomy.

I like making the links to sections of the report explicit by including (Section x) in the text.  Not all of your links are to sections, so a reader doesn't know whether a hyperlink is an internal or an external link.  I also think we still want it to be possible for someone to print out your thesis and read it.  Hyperlinks won't work from a printed document, but the in-text pointers (Section x, etc) will direct the reader.

**Comment by samm82** [comment]
I'll polish off these remaining todos, then create a new issue explicitly for @JacquesCarette's review! 😁
