### ISSUE TITLE
Dr. Smith's Review of Methodology Section

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#112]
**Links**: [thesis](https://github.com/samm82/TestGen-Thesis/blob/main/thesis.pdf) and [paper](https://github.com/samm82/TestGen-Thesis/blob/main/paper.pdf)
**Methodology**: Chapter 3 of thesis and Sections III-A to III-D of paper

I think there is some significant work to be done here in terms of formalizing the terms/procedure I used for data collection (#102), but I wonder if this would be more fruitful to discuss after a review of what I've already written in that regard. Then we can more clearly see what areas need to be expanded upon. If you start reviewing and realize a large oversight early on, feel free to stop reviewing so I can address feedback more generally to be more efficient! In the meantime, I'll start working on my seminar slides with the goal of having something to discuss during our meeting next week!

**Comment by smiths** [comment]
@samm82 here is my review of Chapter 3.  We can discuss it during our meeting today.

[Sam_thesis_Ch3_Fdbck_Smith.pdf](https://github.com/user-attachments/files/17995145/Sam_thesis_Ch3_Fdbck_Smith.pdf)

**Comment by samm82** [comment]
From #121: I should try to reduce cross-referencing, including local examples (even just ONE), so the reader doesn't have to do as much navigation. I should also have a general overview of my methodology, which will help with the reproducibility (done for my seminar in #116 lol); improving how well this research can be reproduced is a good goal even if we don't explicitly test it.

**Comment by smiths** [comment]
@samm82, the points to other parts of your work (like tables in other chapters) is fine to keep.  I just want you to add a local example so the reader doesn't have to follow the pointers to understand the current narrative.  :smile:

**Comment by samm82** [comment]
Sounds good! I just meant this as a "sanity check"; if a paragraph keeps referencing another section, either I should pull over one example OR re-evaluate if it's in the right spot! 😅
