### ISSUE TITLE
Committee Meeting/Seminar under version control?

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#113]
I've started the process of making seminar slides and realized that my committee meeting presentation wasn't under version control. Do either of you remember if there was a reason for this? It probably doesn't make sense to add it now since it's so outdated. I'm not sure if there was a policy reason, a privacy reason (since it involves other profs), or just a "it won't be super useful to track" reason; wanted to make sure before pushing my WIP seminar slides containing leftovers from this presentation!

**Comment by smiths** [comment]
@samm82, no there is no reason not to have committee meeting slides under version control.  You don't have to retroactively add the previous slides, but putting the new slides under version control makes sense.

**Comment by samm82** [comment]
Added on the [`seminar`](https://github.com/samm82/TestGen-Thesis/blob/seminar/seminar.pdf) branch!
