### ISSUE TITLE
Thesis Meeting | Oct 22, 2024 - 2:30pm - Teams

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#114]
Pretty much all there is to talk about are review items, either on my thesis or my seminar slides. I only have a couple specific questions on my slides, based on guidelines given in the `beamer` documentation:

1. I've _always_ ignored advice to _not_ go through lists piecewise (given in the screenshot below). I always find that throwing that amount of text all at once just causes the audience to read it and ignore you. To me, piecewise allows for a "gentler" pace and for me to add context to the items, while still allowing them to act as a visual aid for people if they zoned out or didn't have time to write something down. Thoughts? Should I swallow my pride on this?
2. Also in the screenshot below, apparently footnotes should always be avoided. Is this still the case for URLs or notes that apply in multiple places? 
![Frame Structure Guidelines](https://github.com/user-attachments/assets/dc49d5cf-3665-4443-b268-6ad08d6badad)

---
@JacquesCarette had a scheduling conflict and won't be able to make it; I think if there's one meeting to miss, this is it! 😅

**Comment by smiths** [comment]
@samm82 I don't like uncovering lists piecewise. It slows things down unnecessarily.  If you don't want people distracted by your slides, the key is to make the slides relatively simple. If there is a lot of text, they might read and be distracted, but if there are simple bullets they will skim it quickly and return their attention to you.  We can discuss further tomorrow.

For footnotes, I completely agree.  They don't make sense in a presentation.

**Comment by samm82** [comment]
Some general content notes: telling "my story" shouldn't focus on Drasil, but rather rigorous testing (generated or otherwise). A particular area to focus on is "why does a lack of standardization matter?"
 - consider this in other fields: similar but conflicting definitions of force? isotope? phalange?
 - treat testing like a science (implied by software engineering!)
 - teaching: consistency between schools? industries?
 - [ ] find some more concrete case studies of testing "gone wrong" because of terminology (akin to rocket explosion case studies used to "pitch" engineering)

As for my questions:

1. Going item-by-item has the temptation to speak on a bullet point "until I'm done". As long as I watch this it _might_ be OK to continue doing this, but it's likely a symptom of having too much on a slide (to be revisited later once I've updated by slides' content).
2. I also (now) completely agree. 😁

**Comment by smiths** [comment]
> * [ ]  find some more concrete case studies of testing "gone wrong" because of terminology (akin to rocket explosion case studies used to "pitch" engineering)

Would be great if you could find an example like this, but this could be difficult to track down.  Don't stress if you can't find it; You don't need an example like this to motivate your work.
