### ISSUE TITLE
Category discrepancy of "artifact" surrounding proofs of correctness

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#119]
Based on the definition in IEEE2017 below, I classified correctness proofs as an artifact _and_ a technique

![image](https://github.com/user-attachments/assets/679b0205-6591-4072-8a1e-a2f5ec881b96)
![image](https://github.com/user-attachments/assets/c6621cc9-c52b-4974-9982-7601a8d74d8e)

1. Is it even worth including the category of "artifact"? Is this meaningful/does it follow logically from the definition?
2. If we include this category, does the fact that a proof can be an artifact or a technique really a discrepancy?

**Comment by smiths** [comment]
@samm82 I like the category of artifact.  Your original motivation was for Drasil, and Drasil is all about artifacts.  :smile:  I don't think a proof being an artifact and a technique is a discrepancy.  There are techniques for doing proofs and the proof is only relevant if someone can write it down for others to inspect.

I wondered if all techniques automatically have an artifact.  The results of all techniques are written down somewhere, but there isn't a one-to-one mapping between all techniques and an artifact.  Unit testing doesn't lead to a unit testing artifact.  There will be code that outputs the results of the unit tests, and the results will likely be summarized in a testing report, but that testing report will likely cover more than just the unit tests.

**Comment by samm82** [comment]
I believe this can be closed as of #121
