### ISSUE TITLE
Explain synonyms better

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#124]
As mentioned in #123, I should:

- [x] Include a brief description of what a "synonym" is (i.e., that I'm not redefining it in a weird way)
- [x] "Lay out the criteria [used] for identifying synonyms", including implicit ones

**Comment by samm82** [comment]
@smiths I have implemented our discussion on defining synonym into my thesis (Section 3.2.2) and paper (Section III-B2) that I think covers everything. In particular, there are some to-do notes in the thesis version with some questions. If my changes are sufficient, feel free to close this issue!

**Comment by smiths** [comment]
Looking over Section 3.2.2 on its own, it sounds good.  I'll better be able to judge when I read it in the full context of Chapter 3.  You've done the assigned task, so we can close this issue.  :smile:
