### ISSUE TITLE
Thesis Meeting | Dec 17, 2024 - 2:30pm - Teams

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#125]
# Schedule
Chapter update: I've been working on my Tools chapter; parts of this has required going back to the Methodology chapter and tweaking (since information would be better captured there). My goal is to get the Tools chapter ready for review, then implement the (yet unimplemented) Methodology chapter feedback while I wait. I could also prioritize work on the Tools chapter if that would be better.

_Following discussion based on (quoted) feedback from #112_

# Process Formalization
How do I specify my process "so that someone could reproduce [my] … results"? Dr. Smith gives the following specifics:
- _"How were more [textbooks] added?"_ Honestly, not super sure; a cursory glance at git history suggests:
  1. Dennis et al. (2012) was added for acceptance testing/approach categories
  2. Kaner et al. (2011) was added as evidence for the consequences of ill-defined terminology (in the little bit I read, it took shots at SWEBOK; I think this is a good source to investigate more thoroughly, but time may not allow this)
  3. Gerrard and Thompson (2002) was added since it was the OG source for info from ISTQB, used to cross-check
- _"We need to say why we are confident that all of the important test approaches have been identified"._ At this point, I'm not! There are still 172 undefined test approaches, and I STILL haven't come across property-based testing!

The bottom line: in hindsight, this has been a very ad hoc process where I just started by trying something and then learning how to do it better as I go (unfortunately, similarly to my Drasil PR bad habits 😅). A lot of sources were simply added by investigating a specific "thread" of ambiguity or confusion. I get there's a place for "faking a rationale process", but I don't really know how to even fake it!

# Meta-level Collections Term?
I use the term "meta-level collections" to refer to wide collections of terminology with the purpose of presenting an overview, such as Firesmith's taxonomy, ISTQB, and SWEBOK. Is there a better term for this? Just "collections? Will "meta-level" need to be explained upon introduction of this source tier (previously source category)? Am I even using the term correctly?

**Comment by JacquesCarette** [comment]
You might want to look up at least [snowballing](https://pmc.ncbi.nlm.nih.gov/articles/PMC2151802/).

"meta-level collections" is not wrong, but feels overly fancy. "Terminology collections" might be more immediately communicative.

**Comment by samm82** [comment]
My attempt at including more context for textbook inclusion (related to the first point in Process Formalization):
![image](https://github.com/user-attachments/assets/90a6927a-f56e-4bc9-9e29-cc29c19e203d)

**Comment by smiths** [comment]
@samm82 during today's meeting, can we also discuss a schedule?  Specifically, when do you anticipate having more completed chapters to review.  You have #111 open, but it isn't clear if the revisions to chapter 1 based on my feedback have been addressed.  Have they?  When will the other chapters be complete?

**Comment by samm82** [comment]
Sounds good! I've been working on my Tools chapter; parts of this has required going back to the Methodology chapter and tweaking (since information would be better captured there). My goal is to get the Tools chapter ready for review, then implement the (yet unimplemented) Methodology chapter feedback while I wait. I could also prioritize work on the Tools chapter if I'm next in your "rotation" from last meeting 😅

**Comment by smiths** [comment]
Sounds good @samm82, but you should also revisit your introduction.  It is challenging for us to review later chapters without your current best guess on what the introduction will look like.

**Comment by samm82** [comment]
Ooh! I misremembered what #111 was; I've implemented your feedback 😁 on those sections

**Comment by smiths** [comment]
So @JacquesCarette can go ahead with is review of that chapter?

**Comment by samm82** [comment]
Despite my internet dropping partway through we made it through everything! 💀

1. Based on how much content needed to be added to the Methodology chapter, I should get that to Dr. Smith for a re-review ASAP (should be this week!) In future I need to be more explicit about when things are ready for review and not leave things ambiguous. 😬
2. Snowballing was a useful technique, but also the fact that I (eventually) started from reasonable starting points (IEEE, SWEBOK, etc.) and then explored other areas (essentially performing mini lit reviews) where there were gaps (i.e., the in Undef Terms section). The fact that we didn't get to property-based testing is really an argument for the complexity of the domain and the lack of its standardization; this should be included (and I'll probably throw in the rest of terms that I wanted to investigate but didn't have time).
3. I like "Terminology Collections" (and I think @smiths does, too) so I'll pivot to that term.

**Comment by smiths** [comment]
Good summary @samm82.
