### ISSUE TITLE
Sam's Thesis Meeting | Dec 12, 2023 - VIRTUAL

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#15]
Structure of glossary:
1. How should sources be captured? Should it be a LaTeX table?
2. Should the "outcome" of the test be captured at this point, or would that be getting too granular? (See point 4. below)

Review of research on existing ontologies. **NOTE:** You don't need to read the following papers/excerpts for the meeting (although you can if you want); I just want to highlight where this discussion will come from and keep track of it until I upload the papers!

1. Relations between software testing concepts [(Barbosa, 2006, p. 2)](https://www.researchgate.net/publication/221389585_Towards_the_Establishment_of_an_Ontology_of_Software_Testing)<sup>1</sup>
2. Questions from ROoST [(Souza, 2017, pp. 8-9, 12)](https://www.researchgate.net/publication/314268288_ROoST_Reference_Ontology_on_Software_Testing)<sup>1</sup>
3. Term for "intervention" [(Engstrom, 2015, pp. 1-3)](https://ieeexplore.ieee.org/document/7107470)<sup>1</sup>: is it useful? Does it apply to methods like using oracles/equivalence classes?
4. "Test factors" vs. "Results of Testing (Area of Confidence)" column [(Perry, 2006, pp. 40-41)](https://dahlan.unimal.ac.id/files/ebooks/2006%20[William_E._Perry]_Effective_Methods_for_Software_SANGAT_BAGUS.pdf)<sup>1</sup>; revisiting from #14 but actually writing down our discussion 😅

<sup>1</sup>I'm assuming it would be helpful to upload resources used to my repo somewhere? In a `papers/` folder, named like the BibTeX references for them? I'm sure using natbib style would also help with traceability (#7).

**Comment by smiths** [comment]
Yes, the natbib style for citations is nice because it contains some useful information (author and year) right where the citation is located.  It is a good idea if you have a file for a paper that you use the same naming convention.  It does help with traceability.  That is what I've tried to do in the [pub repo](https://gitlab.cas.mcmaster.ca/smiths/pub).  I slipped a few times, but most of the files have natbib style names.

If there are files that would be helpful for @JacquesCarette and me to read, it is a good idea to put the paper somewhere, or link to its public version, when that exists.  For files that don't have a public version you can't put them in a public repo, but you could put them in a private repo, like the pub repo mentioned above.

**Comment by samm82** [comment]
@smiths If there are some papers that are public and some that I've had to request access to on ResearchGate, would it make sense to store all related papers in a pub repo so that they're in one place?

**Comment by smiths** [comment]
It is fine to store publicly available papers in your repo, but I find that I don't do it.  I keep a bib file ([References.bib](https://gitlab.cas.mcmaster.ca/smiths/pub/-/blob/master/References.bib?ref_type=heads)) in my publications repo.  If there is a public link it is stored with the reference.

**Comment by samm82** [comment]
It looks like email notifications are set up on an individual basis. Would you like to be signed up for them as well @smiths?

## Formatting
The format of the glossary should be trivial to parse and easy to add to. CSV probably makes sense for its flexibility, and using natbib will allow for an unambiguous traceability to sources. I should make a private GitLab repo for publications so they are all in one place and named consistently. If possible, publicly available sources (e.g., Google Scholar) should be found, but if the only way to get access is through McMaster or through requesting it, it's private.

## Test Factors/Area of Confidence
The test factors from Perry might not be complete, independent, or comprehensive, but they may be useful as part of the "area of confidence" analysis; regardless, this is something to potentially return to. For now, either this "area of confidence" (or software quality, as I've been implicitly using it!) information can be left to the analysis phase, or recorded in these "simple" terms as a reminder to go deeper in the analysis phase

## Research
I should be looking "forward" to see if any resources (particularly ROoST) have been cited in more recent works! I should also be doing an "active search" by writing down what I do and what process(es) I use. For example,
- realizing that making this glossary is a "subsubtask"
- following citations (e.g., [1] from Engstrom)
- "looking forward", as mentioned above

Regardless, we noted that the notion of "intervention" from Engstrom likely isn't useful to us (or, at the very least, is out of scope) since it is too meta. I wondered about how it related to equivalence classing, but Dr. Carette pointed out that it is still a "live question", since it is something that could be generated, and isn't just an out-of-scope process for designing test cases.

**Comment by smiths** [comment]
Nice summary of the meeting @samm82 and yes, please add me to email notifications as well.

**Comment by samm82** [comment]
Closing since this meeting has occurred and items are either in progress or to be revisited later.
