### ISSUE TITLE
Sam's Thesis Meeting | Dec 19, 2023 - VIRTUAL

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#18]
My main work this week has been filling in [my glossary](https://github.com/samm82/TestGen-Thesis/blob/main/Testing%20Glossary.csv) with information I have already documented. If you think a "peer review" would be beneficial, I'm good with that! There are also some gaps to be filled in later that we could discuss if any stand out. I have some specific questions below, which will likely be answered with time and more research, but figured it wouldn't hurt to provide them to potentially get the ball rolling!

1. Level of granularity
   1. Data Testing
   2. Reviews
   3. Path Coverage
   4. Mutation
   5. Regression
2. Parent relations
   1. Regression testing: can be white- or black-box, so child or both or N/A?
   2. Metamorphic testing: seems to be black-box for the code and white-box for the tests; is the "transparency" of the testing defined in relation to the test subject?
3. Confusion on terms
   1. Data testing vs. data coverage in Patton2006 (the same thing, or testing = black-box and coverage = white-box?)
   2. White-box testing (structural analysis/testing) in Patton2006 vs. structural = white-box in other places (see also #1)
   3. Black-box testing ("specification"/functional testing) in Patton2006 vs. black-box in other places (e.g., "functional testing" for FRs)

**Comment by smiths** [comment]
Thank you @samm82 for preparing for our meeting tomorrow.  I had a quick look at your glossary.  It is good to see you working on it.  A few questions come to mind.  I think some of them overlap with your questions above:

- what is the methodology you are employing to make sure that you don't miss any terms?
- what does it mean for a method to be a parent of another method?  Are we sure we will have a hierarchy?
- did you make any progress on the papers we discussed last week?  Did they have any methodologies or results that we can borrow?
- will there be another document besides the glossary?  We talked about tracking other data for the types of tests, like the required inputs.

**Comment by samm82** [comment]
Brief answers before I go to bed (we can elaborate tomorrow):

- Right now, I was essentially just moving all my previous research into this new format. Going forward, I am planning to revisit the sources (I think there are about 5 left to do; I've already gone through Patton2006) and keep track of "duplicated" information (e.g., definitions that are present in different sources) or "conflicting" information (e.g., a term being used to describe two different things). Then, I'll continue following more papers to see what else is out there, including their sources and papers that source them; not sure how to do this "completely".
- A child of a technique is essentially a "refinement" of it (an obvious example is that "static black-box testing" is a child of "black-box testing"). I am not sure how useful this information would be, but figured it may be nice information to track to get an idea of how the literature "hierarchs" them and could provide a column to sort this glossary by in future.
- I haven't yet gone through the papers we discussed previously (or the "glossaries" Dr. Carette provided previously, which I'll likely do first), but as mentioned above, they are coming up on my to-do list.
- Yes, eventually there will be another document beyond this. The format, information, and scope are yet to be decided; my initial thought is that this document could be "filled out" as we uncover patterns/ambiguities to be more like the original vision for this work and that it would grow over time (which would also be a nice way to work on it incrementally), but we can discuss this more.

**Comment by samm82** [comment]
The main takeaway here is to figure out/record my methodology. It is likely worth it to describe my ad hoc approach at the beginning (starting at well-known books within the McMaster context) but then outline the "switch" to start from more "established" resources (e.g., IEEE, SWEBOK) then "snowballing" to other resources. Of course, I should also look into other methodologies to see if there is something out there that would be a better fit.

To make sure that this isn't redundant work, we should make _sure_ that this hasn't been done. I realized that "survey" is a good keyword to search for this kind of work that I didn't look for before (I mainly focused on "taxonomy" and "ontology"), but if I am unable to find a satisfactory one, reaching out to SE.StackExchange might be a good idea. As far as learning about other techniques (and capturing as many as we can!) goes, looking into the papers from our last meeting (#15) and asking ChatGPT may be good next steps.

A minor note: Dr. Smith pointed out that it would be nice to reserve the word "formal" to refer to "formal math", so changing "formal reviews" to "structured" or "systematic" reviews may be nice. Obviously, we should record what the literature uses, but this is something to keep on the back burner for now, and to record so I don't forget!

**Comment by samm82** [comment]
I expanded on my methodology in 6a343eb; the bit about "snowballing" or finding other sources isn't really captured yet
