### ISSUE TITLE
Sam's Thesis Meeting | Jan 15, 2023 - 10:30am - ITB 167 

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#19]
I've started a more [systematic glossary of types of testing](https://github.com/samm82/TestGen-Thesis/blob/main/Systematic%20Testing%20Glossary.csv) based on [ISO/IEC/IEEE 29119-1](https://gitlab.cas.mcmaster.ca/crawfs1/TestGen-Thesis-Papers/-/blob/main/IEEE2022.pdf?ref_type=heads) (referred to as "IEEE" throughout this issue), referencing other sources as appropriate. 

## Questions about scope
1. IEEE talks about "test processes" (p. 24), which I think are more general than what we're looking for and may be out of scope.
2. IEEE seems to differentiate between "testing approaches" and "test design techniques". Since this confused me before (see point 3 in #11), I'm recording this information (at least for now).
3. IEEE identifies some types of testing as "test types", meaning they are "focused on specific quality characteristics" (p. 15), and some as "practices" (p. 22). Are these significant things to record/keep track of? My hunch is "no".
4. Figure 1 on page 17 decomposes "Verification and validation" into "Static testing", "Dynamic testing", "Demonstration", and "V and V analysis"; my gut reaction is that the last two are out of scope, but I wanted to double check.

## Other things of note from IEEE
1. Page 18 gives some purposes of testing (detecting defects, gathering information, and creating confidence) that may serve as a good basis for future categorization/analysis.
2. Page 31 lists some examples of test metrics: residual risk, cumulative effects, test coverage, defect detection percentage.

## "Handled" discussion
1. Compatibility testing's definition implies the existence of "co-existence testing" and "interoperability testing"; IEEE uses the latter three times (pp. 22,43), although I think they really mean "co-existence testing" the third time. ISTQB seems to support that "compatibility" encompasses "co-existence" and "interoperability" (and may even just be their union!) so it may be worthwhile to introduce a "new" term (or at least investigate this in more depth). **I've added both of these terms to the document.**
2. "Branch testing" is listed in IEEE, as opposed to "branch coverage" that I've seen in many other sources. Interesting (and important!) to note that _coverage_ is a metric of the extent of the _testing_ (at least how I understand it). **Confirmed by @smiths.**

**Comment by smiths** [comment]
Thank you for the update @samm82.  Are there columns still to come in your glossary summary table?  I like it, especially the traceability to the source of the information.  However, I feel like we discussed other columns like inputs, whether an oracle is required, etc.  I'd have to look at my notes, but I'm hoping that you took the same notes and will be adding the columns.  :-)  

If you want to discuss compatibility/interoperability etc tests, it would be helpful if you added them all to your summary table.  Compatibility is there, but not co-existence or interoperability.

Yes, coverage is a measure of the extent of testing.

**Comment by samm82** [comment]
Yes, more columns are coming! In my previous attempt, I had an "inputs" column. I'm planning on filling that in once I have a more "complete" list; right now I'm just in a data-gathering phase.

I'll add rows for "co-existence" and "interoperability" testing!

**Comment by smiths** [comment]
Great!  Thanks @samm82.

**Comment by samm82** [comment]
@smiths @JacquesCarette I think I've done all on this that I will have done before this meeting if anyone is interested in looking at the document/my updated agenda. I've finished going through the main section of the IEEE source, although there are still the "annexes" that contain examples and may have more information. So far, I have collected 93 types of testing, some of which were described but not defined in the IEEE document; I'll find definitions for these as I continue my research.

**Comment by samm82** [comment]
The main takeaways here are that I should be explicitly recording (a) what's out of scope (and why!), such as the distinction of "test processes", and (b) points of confusion that arise from this research (even if they get resolved later), since this is valuable information that also justifies this work! The distinction of "test types" is also valuable (since it is meaningful from a testing perspective) and avoids having to redo work later on. (A side note for me, I should be defining the different "Field of Testing" values.) ChatGPT may also provide some future threads to unravel (e.g., new types of testing to investigate).

Looking for potential venues for publication will also help inform our scope; is this I should be looking into or is this more in your wheelhouse?

**Comment by samm82** [comment]
Worth noting that I added a list of points of confusion from this source in f9ac41b; there were seven within the document and four between other sources!

**Comment by smiths** [comment]
> Looking for potential venues for publication will also help inform our scope; is this I should be looking into or is this more in your wheelhouse?

I don't have a venue to suggest.  @samm82 it would be good if you did some research on some potential venues.  A conference/journal on testing, or possibly one on software engineering, would be a good fit.
