### ISSUE TITLE
Names for SWEBOK paper/citation

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#20]
I'm not sure if I should name the SWEBOK paper/BibTex citation "SWEBOK", "SWEBOK2014", or "BourqueAndFairley2014" (based on the preferred citation given from the SWEBOK website). I think the last one is the most consistent, but calling it something more recognizable might make it easier to find. Thoughts?

**Comment by smiths** [comment]
An argument could be made for each option.  Bourque and Fairley are the Editors, not the authors, so I think I'd go with your SWEBOK2014 option.  As you said, the name SWEBOK is automatically recognizable.  I like adding the year because there are different versions of the guide.

**Comment by samm82** [comment]
One extra point I forgot to mention is that because of their role of editors, this source gets cited as "Bourque and Fairley, 2014", which is consistent with how they want it cited on [their website](https://www.computer.org/education/bodies-of-knowledge/software-engineering). Would this swing you towards the other option? @smiths I guess it's also worth noting that this is mainly an internal distinction that only affects the paper's name in the GitLab repo and the BibTex entry's name throughout my thesis docs in this repo.

**Comment by smiths** [comment]
The editors won't really care what we internally label the citation, as long as we cite it properly in the generated document.  Either option is fine.
