### ISSUE TITLE
Scope of Testing (vs. V&V)

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#22]
I believe we skimmed over this for time, but the following was a question I had about IEEE2022:

> Figure 1 on page 17 decomposes "Verification and validation" into "Static testing", "Dynamic testing", "Demonstration", and "V and V analysis"; my gut reaction is that the last two are out of scope, but I wanted to double check.

Going through IEEE2017 (I've gone through A-E in the glossary so far 😅), I found similar terminology that seems on the boundary of our scope. Should I include these terms as "test approaches", or are they out of scope?

- **application requirements verification and validation:** a "subprocess that confirms that the application specific requirements are consistent and feasible and ensures that the bound variants satisfy the specific product's requirements" (p. 23)
- **architectural design review:** a "joint acquirer‐supplier review to evaluate the technical adequacies of the software architectural design as depicted in the software design descriptions" (p. 26)
- **certification:** a "third‐party attestation related to products, processes, systems, or persons" or "guarantee that a system or component complies with its specified requirements and is acceptable for operational use" (p. 63)
- **checklist analysis:** "a technique for systematically reviewing materials using a list for accuracy and completeness" (p. 67); it seems like this has a context broader than testing, since it is originally from _A Guide to the Project Management Body of Knowledge_. "Checklist-based testing" is already in my glossary, but this definition narrows down to accuracy and completeness instead of allowing the testing to be "focused on ... [any] particular quality characteristic" (IEEE, 2022, p. 34)
- **code tuning:** the "process of making statement‐level changes to a program to make it more efficient" (p. 74)
- **design review:** a process "to determine if the design meets the applicable requirements, to identify problems, and to propose solutions" (p. 132); also _detailed design review_
- **documentation reviews:** "the process of gathering a corpus of information and reviewing it to determine accuracy and completeness" (p. 144); also from _A Guide to the Project Management Body of Knowledge_
- **error seeding:** The "process of intentionally adding known faults to those already in a computer program … [to] monitor[] the rate of detection and removal, and estimating the number of faults remaining" (p. 165); SWEBOK classifies this as a "Test-Related Measure" (2014, p. 93)

Semi-related:
- **data analysis:** the "systematic investigation of the data and their flow in a real or planned system" (p. 114)
- **domain analysis:** the "analysis of systems within a domain to discover commonalities and differences among them" (p. 145)
- **dynamic analysis:** the "process of evaluating a system or component based on its behavior during execution" (p. 149)

**Comment by JacquesCarette** [comment]
I would agree that for your Master's thesis, the last two are out of scope. (Nevertheless, thinking about how to do them in a generative context is kind of fun -- generating a video-demo of a piece of code being used is not impossible!)

Again, for your Master's, I would consider all but 'error seeding' out of scope, although for a paper reviewing testing in general, they probably aren't.

Amusingly "domain analysis" is core to Drasil but is out of scope for your work. Dynamic analysis is, in some sense, very core to your work.

**Comment by smiths** [comment]
I agree with @JacquesCarette.  Most of what you have listed @samm82 is out of the scope of your Master's thesis.  In general, all artifacts should be verified, but the scope of your work should focus on the verification of the code.  You should make that explicit in your writing.  Giving examples of items from your list that are out of scope will help the reader understand the distinction you are making.
