### ISSUE TITLE
How "exhaustive" is path testing *really*?

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#3]
From [my thesis notes](https://github.com/samm82/TestGen-Thesis/blob/main/notes.pdf) (currently p. 28):

> If done completely, it “is equivalent to exhaustively testing the program” [7, p. 421]; however, this seems to overlook the effect of inputs on behaviour as pointed out in [8, pp. 466-467]

Elaborating on Peters [8]*, the example of zero division is given; this wouldn't be uncovered by path coverage (unless a specific branch was added to check if `x == 0`, for example), so "exhaustively testing the program" _actually_ requires full path coverage with **all** possible inputs, which it seems like van Vliet failed to account for. Thoughts? (See what is currently Q5.)

---

<sup>\*Don't worry, I have a note to use natbib; just haven't gotten there yet. Apparently the issue with my laptop was the motherboard and they said it could be fixed soon, so I'm holding off on more "intensive" work (like running VS Code/LaTeX 😂) until then.

**Comment by smiths** [comment]
@samm82 I agree that path coverage is not equivalent to exhaustive testing.  I agree with your argument.  Although I don't remember the details, Ghezzi et al (2003) (Fundamentals of Software Engineering) present a formal view of testing that shows that the only way to guarantee correctness is with exhaustive testing.  You can have path coverage without testing every possible input.  Maybe Van Vliet was eluding to the fact that path coverage is typically as infeasible as exhaustive testing?  Path coverage is fewer tests than exhaustive, but it is still a potentially ridiculous number of tests.

**Comment by samm82** [comment]
Either way, I'll make a format note of this depending on how it comes up in my thesis, especially highlighting the possibility of confusion (i.e., "we have full path testing, so we must have tested everything!") and why path coverage =/= exhaustive testing.

Thanks for the reminder to look into Ghezzi et al (2003)!
