### ISSUE TITLE
Definition of "operational" vs. "operational acceptance testing"

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#36]
I have come across the terms "Operational Testing" and "Operational Acceptance Testing", but can't nail down their difference. Some sources treat them as synonyms, including:

- [Some](https://itrinegy.com/why-you-need-to-embrace-operational-testing/) [blogs](https://www.tutorialspoint.com/software_testing_dictionary/operational_testing.htm)
- [A testing platform](https://www.lambdatest.com/learning-hub/operational-testing)
- [A paper from the University of Arizona](https://repository.arizona.edu/bitstream/handle/10150/607608/ITC_1996_96-01-4.pdf?sequence=1&isAllowed=y) and
- Potentially a paper about a precipitation accumulation gauge ([download](https://ams.confex.com/ams/pdfpapers/69273.pdf))

I have found some differences in usage, though:

## Operational Acceptance Testing
- It isn't defined in IEEE 2022, but is listed as a subset of acceptance testing (as well as on [Wikipedia](https://en.wikipedia.org/wiki/Operational_acceptance_testing) and [that testing platform](https://www.lambdatest.com/learning-hub/operational-testing))
- [ISTQB](https://glossary.istqb.org/en_US/term/operational-acceptance-testing-3-2) defines it as "a type of acceptance testing performed to determine if operations and/or systems administration staff can accept a system"

## Operational Testing
- SWEBOK v3.0 defines it as reliability testing that is "derived by randomly generating test cases according to the operational profile of the software" (p. 4-6) and mentions it can be used for system testing
- SWEBOK V4 omits this definition (potentially because this isn't quite the right definition), but includes it as a subset of usage-based testing (which can be used for acceptance testing)
- [ISO/IEC 2018](https://www.iso.org/obp/ui#iso:std:iso-iec:ts:20540:ed-1:v1:en:term:3.12) defines it as "test[ing] to determine the correct installation, configuration and operation of a module and that it operates securely in the operational environment"
- IEEE2017 defines it as "testing conducted to evaluate a system or component in its operational environment"
- It is kept generally distinct from acceptance testing in [this nuclear fuel project … report?](https://inis.iaea.org/collection/NCLCollectionStore/_Public/34/007/34007552.pdf?r=1)
- It is implied to be a subset of operational acceptance testing on [TutorialsPoint](https://www.tutorialspoint.com/software_testing_dictionary/operational_testing.htm)

Not really sure what the action of this issue is, but figured this was a better place to track it than in a meeting issue 😂

**Comment by JacquesCarette** [comment]
I would be fine to consider these to by synonyms from all you give above. Other than SWEBOX v3.0, the testing occurs in the actual operating environment, so see if it works there. So I'd be inclined to consider "Operational Acceptance Testing" as the main term which can sometimes be shortened.

It does make sense to separate it from acceptance testing IMHO: the latter may well focus (too much) on functional testing. Proper acceptance testing really ought to be about "in situ fit-for-purpose testing" that would then be an umbrella for various kinds of acceptance tests.

**Comment by smiths** [comment]
@samm82 great job digging into many sources to investigate operational versus operational acceptance testing.  You already have something interesting to write about on this topic because you can point out that the definition is far from standardized.  When proposing your recommendation, I think we should follow the advice from @JacquesCarette above.

**Comment by samm82** [comment]
So to clarify, should operational testing be a subset of acceptance testing? I think this makes sense, since "determin[ing] the correct installation, configuration and operation of a module" (from [ISO/IEC 2018](https://www.iso.org/obp/ui#iso:std:iso-iec:ts:20540:ed-1:v1:en:term:3.12)) could be considered a type of acceptance testing, although it is interesting that this refers to it at the module level, not the acceptance level.... We could also consider "operational testing" to be more generic, where "operational acceptance testing" is "acceptance testing to determine the correct installation, configuration and operation of a _system_"?

**Comment by samm82** [comment]
I've summarized the contents of this issue/discussion in b6e3066; if that looks good/sufficient, this issue can be closed! 😁

**Comment by smiths** [comment]
The summary in b6e306625c7e38ca854d3ff954c5e5f8eff39871 looks good to me.  I think you can close this issue.
