### ISSUE TITLE
Review of SWEBOK V4

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#38]
I've formalized my feedback on SWEBOK I had put in the [wiki](https://github.com/samm82/TestGen-Thesis/wiki/Feedback-on-SWEBOK-V4) to [their specific Excel format](https://github.com/samm82/TestGen-Thesis/blob/main/SWEBOK4-SamuelCrawford.xlsx). This template provided space for 40 comments; I had to add nine rows! If you don't have time/brainpower to devote to looking this over, no worries, but I thought I would provide the option (I would focus on entries with a category of "TH", followed by "TL"); the deadline for submission is Feb 16th, so if I don't hear anything by then, I'll submit it. I _did_ have some small questions:

1. I'm assuming I should provide my McMaster email (especially given the next field is "affiliation"); would this be an issue if I lose access to this email? Do McMaster emails get "recycled" or will it be mine for life?
2. One of my points of feedback is "…add a correct definition for 'scalability testing'"; should I provide one? Based on #35, I think we're nailing down what that would look like, but doing so with an "academic" source, like the ones used in SWEBOK, could prove tricky. I'm tempted to leave this in their hands; should I prioritize nailing down a definition with more rigorous sources? Could I suggest one with less rigorous sources and leave it up to them?

**Comment by smiths** [comment]
@samm82 you are right that you should use your McMaster e-mail.  I am 99% sure that you can have automatic forwarding from your McMaster e-mail address to another address when you are no longer a student.  They definitely won't recycle the account name.  It is yours, although I'm fairly sure that they will stop providing storage space after you graduate.  

I agree that you don't have to spell out the definition of scalability.  You've already done plenty with your review comments.

**Comment by smiths** [comment]
@samm82 good job on the feedback for SWEBOK.  Most of it is standard consistency and presentation issues, but you got a few "zingers" in there, like defining usability, but calling it scalability, and citing a source that doesn't even define elasticity testing!

I think you should get credit for this work in some form.  Maybe you can include it as an Appendix to your Master thesis document?

**Comment by samm82** [comment]
That's a good idea! It'll be interesting to see how much of these comments make it into the final cut 👀

**Comment by JacquesCarette** [comment]
Added to my list of things to look at. Not sure if I'll make the deadline.

**Comment by samm82** [comment]
If you don't, not a problem!

**Comment by samm82** [comment]
I realized that there was some more information about testing in SWEBOK that I had missed, since it was more specific to other sections. As of 57cdae8, most, if not all, of the mentioned of testing in this document should be recorded (and of course I came up with more review comments!)

I know this is late, but the email I got about this review said "submit by Feb 16" - does that mean I should submit it tonight, or will it be fine if I submit it tomorrow (before the end of the work day)?

**Comment by smiths** [comment]
@samm82 I'm sure you are fine to submit it tomorrow (Feb 16), especially if you do it before the end of the work day.

**Comment by samm82** [comment]
Just submitted, so I'm closing this issue! Let's hope they like my 63 review comments 😅

**Comment by smiths** [comment]
I hope they give you feedback @samm82.  You put a nontrivial amount of time into your review.

**Comment by JacquesCarette** [comment]
Great stuff.
