### ISSUE TITLE
Find conferences/journals to publish in

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#42]
I've created a [wiki page](https://github.com/samm82/TestGen-Thesis/wiki/Publication-Venues) with more in-depth research into publication venues discussed in #24 and #41. Feel free to add thoughts here and/or suggest other ways to present this information! @smiths @JacquesCarette

**Comment by smiths** [comment]
The summary looks good @samm82.   You don't need more information.  What you have provided is enough for our conversation.  We can put this discussion on the agenda for our next meeting.  (Thank you for explaining C*; I was wondering about that.  I thought it was a typo.)  :smile:

**Comment by JacquesCarette** [comment]
Quick look:
- C3S2E24 is a B tier (if not C tier) conference. This would be fine for some "lesser work" that we still want to put out there, but your work seems to be better than that.
- ICSME is definitely a real conference. Not quite A tier, but good enough.
- SEKE: not as awful as C3S3E24 but the PC is rather unimpressive.
- SOFT 2024 using the same 'line' as ICSE is already a very bad sign. Definitely C tier.

All the journals seemed good to me.

**Comment by smiths** [comment]
I agree with the feedback from @JacquesCarette.  I actually presented at SEKE at the beginning of my career.  I didn't realize that it wasn't a great conference.  :-)  It wasn't terrible, but I think we can do better.  :-)  @samm82 we already briefly discussed SOFT.  They feel like a predatory conference to me.

**Comment by samm82** [comment]
How should I track this discussion in the wiki page? Make a section for conferences we likely won't pursue? Remove them altogether?

**Comment by JacquesCarette** [comment]
Remove.

**Comment by samm82** [comment]
BTW, I added [QRS 2024](https://github.com/samm82/TestGen-Thesis/wiki/Publication-Venues#qrs-2024-the-24th-ieee-international-conference-on-software-quality-reliability-and-security-website) as a conference to potentially consider, although it is in the UK; not sure if you get notifications for wiki edits @smiths @JacquesCarette

**Comment by JacquesCarette** [comment]
No, wiki edits don't trigger notifications.

**Comment by JacquesCarette** [comment]
This is surprisingly 'second tier'! It's harder to tell, but the fact that the (vast) majority of the organizing people are from non top-100 universities is the biggest hint.  [ESEM](https://conf.researchr.org/track/esem-2024/esem-2024-technical-track) seems better. As does [ISSTA](https://conf.researchr.org/home/issta-2024)

**Comment by smiths** [comment]
@samm82 let's start our next meeting with a discussion of where to publish.  If we aim for ISSTA, the deadline is very close.  Even the ESEM deadline is fairly tight.

**Comment by samm82** [comment]
Sounds good! I have looking into these areas on my to-do list for today (and will do so soon! 😅)

**Comment by samm82** [comment]
I've updated the wiki page, added important information for the conferences that were already there, and added ICCSIT 2024 (which I'm 99% sure we'll discard)

**Comment by samm82** [comment]
In #44, we decided on the 47th International Conference on Software Engineering ([ICSE 2025](https://conf.researchr.org/home/icse-2025)); if this doesn't pan out, there will likely be a related workshop we can submit to. We'll aim for sometime in June as an internal deadline, and the specific purpose/title of this paper will become apparent as this research progresses, although it will likely be along the lines of "software testing terminology is messy, vague, and unorganized; here is a better way to classify/talk about software testing".

I'll likely add my scripts for finding/assessing conferences to this repo in case others may benefit from them

**Comment by smiths** [comment]
That is an interesting fact about ICSE's committee.  I wouldn't read too much into it though.  I had a look at the [research track committee](https://conf.researchr.org/committee/icse-2025/icse-2025-research-track-research-track).  There are businesses like Google and Microsoft represented.  They wouldn't show up on top 100 university lists, but they are relevant for an SE conference.  You also raise a good point @samm82 that a university can be strong in software, but not be a top 100 university overall.

**Comment by smiths** [comment]
> I'll likely add my scripts for finding/assessing conferences to this repo in case others may benefit from them

Yes, do this.  The problem of finding a good conference comes up all the time.  I'm sure others would be interested in your scripts.
