### ISSUE TITLE
 Thesis Meeting | Apr 15, 2023 - 10:30am - ITB 167 (or Teams?)

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#49]
Starting going through ISTQB led me on a side quest to go through [ISO/IEC, 2023a](https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-2:v1:en), which I finished up recently (this source mainly focused on software qualities, but I got some relevant information about testing).

**NOTE:** Last I checked, I had a bit of a fever (will check again later tonight) and have had a headache the last couple of days. 😔 Depending on how I'm feeling in the morning, I will likely be able to come in person (and will mask up), assuming you are comfortable with it; otherwise, I'm OK to have this meeting virtually.

# General Agenda Items
1. Poster competition: expectations, format (some examples were emailed recently), focus?
   - Rationale
   - Metrics of my research (e.g., hierarchies, static vs. dynamic, qualities, approach categorizations)
   - Highlights of discrepancies
2. Overview of relevant changes from [ISO/IEC, 2023a](https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-2:v1:en) (from the Foreword):
   - Usability and portability have been replaced with interaction capability and flexibility respectively.
   - Inclusivity and self-descriptiveness, resistance, and scalability have been added as subcharacteristics of interaction capability, security, and flexibility respectively.
   - User interface aesthetics and maturity have been replaced with user engagement and faultlessness respectively.
   - Accessibility has been split into inclusivity and user assistance.

**Comment by samm82** [comment]
UPDATE: I'm currently right on the cusp between fever and not fever (37.2°C), at least from what I can tell 😅

**Comment by smiths** [comment]
I hope you are feeling better today @samm82.  I'd be happy to see you in person, but if you can't make it, we can do a virtual meeting.

**Comment by JacquesCarette** [comment]
Ditto. And (sigh: as usual) I'm running late this morning.

**Comment by samm82** [comment]
Sorry for the late notice, but I will be on Teams this morning @smiths

**Comment by samm82** [comment]
The general takeaway from this meeting was what I should be looking for in my poster. See #50 for more details on my actual ideas on how to meet the following requirements:
What's the topic/takeaway? How will I communicate that story?
  - starting from not knowing anything to understanding my point
  - MESSAGE: "the mess of software testing terminology"
     - can be communicated through coloured/organized quote boxes
        - short descriptions to give (needed) background information
        - I'll be there to explain further
        - incomplete definitions could be accompanied by "huh?" to highlight the absurdity/provide some humour
     - good examples going to bad examples (blue -> yellow -> red)

There shouldn't be a lot of text
  - should be readable from far away
  - should use bullet points, not paragraphs
  - any graphics should support the message and not be arbitrary
     - diagram of my process?
     - graphs of what I've noticed (e.g., missing defs in IEEE2022?, types/severities of review issues of SWEBOK V4?)
