### ISSUE TITLE
 Thesis Meeting | May 27, 2023 - 10:30am - ITB 167

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#55]
After some time away, I finally finished going through ISTQB! 🥳 These are my main questions that arose:

# (Our) Definition of "System"
Since we're only looking at code, it makes sense that our definition of "system" would only include the software. However, I think this would effect definitions of several (already quite similar) terms; we could either assume these to be synonyms for our scope and explicitly say this, or keep a general definition of "system" (including hardware, etc.) and keep (at least some of) these as separate:
- **System Testing:** "Testing conducted on a complete, integrated system to evaluate [its] compliance with its specified requirements" (IEEE, 2017, p. 456; OG 2012; similar in Hamburg and Mogyorodi, 2024), usually in regards to "non-functional system requirements", and verify its behaviour (Washizaki, 2024, p. 5-7)
- **Software Qualification Testing:** "Testing performed on completed, integrated software to provide evidence for compliance with software requirements" (Hamburg and Mogyorodi, 2024)
- **System Qualification Testing:** "Testing performed on the completed, integrated system of software components, hardware components, and mechanics to provide evidence for compliance with system requirements and that the complete system is ready for delivery" (Hamburg and Mogyorodi, 2024)

# Scope Questions
1. "Dynamic analysis": the "process of evaluating a system or component based on its behavior during execution" (IEEE, 2017, p. 149); this doesn't seem super useful, but IEEE (2022, p. 17) makes a distinction between static analysis/testing (with the latter being a sub-category of the first), so doing the same with their dynamic counterparts might make sense?
2. Approach vs. Paradigm (#52)
   a. **Session-based Testing:** Testing "in which test activities are planned" in "uninterrupted period[s] of time"
   b. **Shift Left:** Testing done "as early as possible in the software development lifecycle"
   c. **Shift Right:** "Testing [of] a system continuously in production"
   d. **PRISMA:** "A systematic approach to risk-based testing that creates a product risk matrix" 
   e. **Structured Scripting:** "Scripting … that builds and utilizes a library of reusable (parts of) scripts"
3. Descriptors vs. Separate Approaches
   a. **Structured Scripting:** "Scripting … that builds and utilizes a library of reusable (parts of) scripts"
   b. **Offline MBT:** "Model-based test approach whereby test cases are generated into a repository for future execution"
   c. **Online MBT:** "Model-based test approach whereby test cases are generated and executed simultaneously"
   d. **Usability Test Script(ing):** The creation/use of "a document specifying a sequence of actions for the execution of a usability test"
4. We decided that "evaluation" was too vague to be useful (#39); what about these sub-terms?
   a. _Formative:_ "designed and used to improve the quality of a component or system, especially when it is still being designed"
   b. _Summative:_ "designed and used to gather conclusions about the quality of a component or system, especially when a substantial part of it has completed design"
   c. _Usability:_ the gathering of usability information; a superset of the previous two
5. **System Hardening:** "The step-by-step process of reducing the security vulnerabilities of a system by applying a security policy and different layers of protection"; could some of these "layers" include testing, or is this too vague?
6. Different types of attacks (as a sub-approach of the Attacks approach)?
   - e.g., account harvesting, password cracking, pharming, phishing, security attacks, SQL injection
   - What about less-related terms (e.g., reconnaissance, footprinting)?

# Further Reading
ISTQB cites _Risk-based e-business testing_ by Gerrard and Thompson from 2002. [Google Books](https://books.google.ca/books?id=54UKereAdJ4C) has a preview, but McMaster doesn't have it, although [other universities](https://search.worldcat.org/title/1105544728) do; would it be worth it to try and borrow it, even though it's so old? There also seems to be a (slightly older) [paper version](https://www.agileconnection.com/sites/default/files/article/file/2013/XUS129342file1_0.pdf) which may be sufficient (and includes some test approaches I haven't come across yet); would this be better/sufficient?

**Comment by smiths** [comment]
The material above should start a good conversation for our meeting.  Glad you are back at it!  One thing that stands out to me after skimming your agenda is that people will add the word testing to anything!  Session-based testing!  We should probably distinguish test techniques that are about ways to reveal important test cases and others.  We should still capture everything, but in our scope pass, we should be able to remove session-based testing.  I think terms like this are more about project management than testing.

**Comment by samm82** [comment]
My takeaways:
1. Define "system" generally and record related definitions as separate terms (for "completeness") - also note that "qualification testing" seems to be more specific to hardware systems
2. For my scope questions, our takeaway is "record _everything_ and analyze later". This includes recording "test processes" (which I have previously called "test paradigms"), which will change #52 from adding these terms as "out of scope" to actually defining these terms, categorizing them as "processes" - a side effect of this is that some previously missed processes (i.e., processes that I have ignored earlier on in my process) may not be captured (for the sake of time/redundancy); this should be made explicit in my methodology section, with the potential to iterate over these sources again.
3. The paper version of this resource is likely sufficient.

I will close this issue once I have addressed these action items 😁

**Comment by samm82** [comment]
Everything has either been addressed, moved to another issue (see #52), or moved to my to-do list (looking at _Risk-based e-business testing_ and discussing points 4 and 5 from the Scope section in our next meeting, agenda to be created later).
