### ISSUE TITLE
"Environmental tolerance testing" seems strictly hardware-related

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#58]
On [pg. 56 of _A Taxonomy of Testing Types_](https://apps.dtic.mil/sti/pdfs/AD1147163.pdf#page=56), all of the examples of environmental tolerance testing seem hardware-focused (and therefore out-of-scope). _Unlike_ domain-specific testing from our last meeting (#56), I can't really think of any potential sub-categories that would be in scope. Is there an obvious example that I can't think of? Should I just make a note of this and leave it out of the table (at least until something comes up that indicates I should include it)?

![image](https://github.com/samm82/TestGen-Thesis/assets/35857611/c13c0ba0-443b-4944-8403-18812140a73b)

**Comment by smiths** [comment]
@samm82 I agree that these tests are out of scope because they are hardware related.

**Comment by JacquesCarette** [comment]
(Sadly?) I disagree. While these are often related to hardware *implementations*, these are also related to hard constraints (and sometimes, soft constraints for comfort, like acceleration and sound levels). I find these to be interestingly in scope!

**Comment by samm82** [comment]
If we take "acoustic tolerance testing" as an example, this seemed to mean (at least at first glance) "can the hardware (e.g., sensors) handle auditory inputs/environments above a certain level?" but based on your comment, it seems like this also refer to "can the software handle and (meaningfully) process auditory inputs, potentially in the presence of 'environmental audio' noise?"

Is this similar to your train of thought @JacquesCarette? Testing in regards to sound levels produced _by_ the system seems to be covered by audio testing and/or comfort testing, whereas this focuses on external sound levels. I could also see how this could potentially be software relevant (e.g., for a noise-cancelling algorithm) but don't want to put words in your mouth.

The bottom-line takeaway is that these shouldn't be dismissed on principle without more investigation on their software-specific implications 😅

**Comment by JacquesCarette** [comment]
I certainly agree with your bottom-line. It may well be that the original sources make it clear that this is all deeply hardware related (then: out of scope). But it seemed like there easily could be a software component too -- though it may well fit somewhere else.

**Comment by samm82** [comment]
Based on my notes from [these commits](https://github.com/samm82/TestGen-Thesis/compare/8b2ea3b3bc77c68381212aab52737f0c7187b4f3..ac5370d75fed3588416dbfd4be039b6dc4d72845), I feel like this category is out of scope. Feel free to re-open this issue if you disagree!
