### ISSUE TITLE
Loop Testing: Control Flow vs. Control Systems

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#62]
When investigating "loop testing" (i.e., the testing of loop structures in code), I stumbled upon the idea of loop testing (as in feedback loops) in control systems. Obviously there is a hardware and software component to the latter, so only some of this testing would be in scope. While these two ideas of "loops" could be seen to be similar, I think there's enough of a distinction to capture them separately (which I've done).

Here is the [relevant commit range](https://github.com/samm82/TestGen-Thesis/compare/4f379d26bf1493b35be58c50d35ed6a13bee0415..36993d7f74a0e0e35d4984998d60367a432d2986); I'd love a second look to make sure I'm on the right track (and not doing unnecessary work 😅).

**Comment by JacquesCarette** [comment]
Seems right to me (you noted it at the right level and moved on.)

**Comment by smiths** [comment]
I agree with @JacquesCarette.
