### ISSUE TITLE
Thesis Meeting | July 8, 2024 - 10:30am - VIRTUAL

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#66]
I'm just going to assume that these meetings will just be between the two of us unless I hear differently from you, @smiths. Sorry this is so late, but I will be virtual tomorrow as well; I'll be back in Hamilton on Thursday!

1. #60
   1. Are we at the point where we can start thinking about what this paper will look like?
   2. Any general guidelines for writing abstracts? (I found [this page](https://conf.researchr.org/track/icse-2023/icse-2023-posters?), but it's from the Posters Track from 2023; would it still be relevant?)
2. #64 
3. #65 
4. Potentially #40, plus future plans

**Off topic:** Sessional position (COMPSCI 2ME3, JO #63349) What would this all entail? Could this be an avenue for me?

**Comment by smiths** [comment]
@samm82, yes it will just be the two of us.  We can have our meeting on Teams.  See you (virtually!) tomorrow.  :smile:

**Comment by samm82** [comment]
All items covered or tracked in other issues. Taking the sessional position could be a good idea, depending on how much work would be required to "adapt" previous content to match the specific goals/calendar items for this course.
