### ISSUE TITLE
Review: Scalability Testing

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#71]
I consolidated all the notes on discrepancies regarding "scalability testing" into one section, currently Section 2.4.5 of my [notes.pdf](https://github.com/samm82/TestGen-Thesis/blob/main/notes.pdf)! (I also reorganized my tracking of discrepancies to aid navigation.) This includes the confusion with "elasticity testing" (#35), but also IEEE2021's claim that it is a synonym with "capacity testing" and the wildly incorrect definition from SWEBOK (which I had captured in my poster but not my thesis).

This currently contains both the problem and my recommendation, which I know is contrary to @smiths's preference in #67, but I couldn't really think of a way to separate them! 😅

This section is probably ready for at least a preliminary review, which will also probably help guide what our expectations are for my thesis going forward! Since I'm thinking it will be bunch of "bite-sized" sections on various subsets of testing, I'll keep track which sections have been reviewed, even if I end up moving them around. Would it be better to do this in the document itself or is something like a separate spreadsheet sufficient?

**Comment by JacquesCarette** [comment]
I don't see either problem or solution here?! I see a narrative of what is found in the literature.  Also: the word 'elasticity' does not occur in this section. So I am quite confused.

In any case, the section 2.4.5 that I read (just downloaded the repo just now) read nicely.

**Comment by samm82** [comment]
I _think_ this is resolved with my work on my paper, so I'm closing this issue. It's probably better to figure out a better workflow for reviewing sections (maybe @smiths and I can discuss during our meeting tomorrow? I'll throw a quick heads-up here that I'll be virtual 😢), in which case we may revisit this.

**Comment by smiths** [comment]
@samm82 I didn't schedule our meeting for tomorrow (Tuesday), so another meeting took the time slot we usually use on Mondays.

Can we meet at 11:30 am tomorrow (Tuesday), on Teams?
