### ISSUE TITLE
Format of Dr. Smith's Name

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#76]
The submission page says "Please enter the authors’ emails, names, and affiliations exactly as they should appear in the ACM Digital Library." It looks like @smiths's [profile](https://dl.acm.org/profile/81324493842) shows up as "Spencer Smith", without a "W." Just making sure this is right! (@JacquesCarette added a "W." as part of his review in #74.)

**Comment by smiths** [comment]
@samm82 I wasn't aware of that rule, but I agree that there is no W in my ACM  profile.  I like the W because with the last name Smith, anything I can do to distinguish myself from the masses is helpful.  :smile:  Based on the rules we'll have to drop the W.
