### ISSUE TITLE
Thesis Meeting | Aug 12, 2024 - **11:30am** - ITB 167

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#83]
I seem to remember wanting to push this meeting later because of Sasha's defense, but I'm not sure if I'm misremembering a previous rescheduling and that was just a note that @JacquesCarette wouldn't be attending. Do you remember if we're shifting our meetings because of this @balacij?

I imagine that points 3. and 4. may require some explanation to articulate my meaning, so I'm glad we have these meetings! 😁

# Agenda

1. Do I need to enroll in SGS 700 for September if I'll (hopefully) be done by the 27th? Apparently the "final date to submit Master’s thesis to departments (prior to Defence)" (from the [School of Grad Studies website](https://gs.mcmaster.ca/current-students/dates-and-deadlines/#tab-content-thesis)); does this mean I'm essentially locked in to another term of grad school, or just that I would be graduating at the spring 2025 convocation?
   - Super minor related note: how much would it impact you two if I didn't attend my convocation? I was recently reminded how boring those kinds of ceremonies are at my brother's grad, but if you would also be there to celebrate, I'll be there! 😁
2. How should I organize sources for "other" discrepancies? This week I've reorganized them (and written code to automatically sum them for my table) into High, Medium, and Low Severity for each group of sources. Is this clear (see Section 5.8)?
3. @smiths mentioned in his review from #74 that "it is unclear how many inconsistencies are within a document and how many are between different documents[, which] is something to consider in the future". What were you thinking for this? This is what I've thought of so far:
   1. Simply sum up how many discrepancies are solely based on a single sources and how many are between different sources.
   2. Combine (i.) with how I currently document discrepancy traceability to document how many are within the same category of sources and how many are between different categories.
   3. Extend (ii.) to also document how many are between any two categories of sources (e.g., instead of just X within category and Y outside of category, split Y into Y1 between category A, Y2 between category B, …).
4. How should we be counting discrepancies (related to 3. above)?
   1. So far, if an "other" discrepancy has multiple conflicts (e.g., both within a category and between another category), it contributes to multiple cells in my table, once for each "level" of conflict. Should this only count once in the sum, or should one bullet point be counted multiple times?
   2. As a counter example to (i.), currently, I sum up the total number of parent discrepancies solely based on the bullet points of the discrepancies, since a parent discrepancy may be explicit _and_ implicit or exist between multiple categories of sources. Should I change this? If I leave this as is, is my footnote sufficient (see Table 5.1)?
5. _(Optional)_ Any areas that stand out to start/continue to analyze from my graphs?

**Comment by JacquesCarette** [comment]
Strictly speaking, I'm on vacation Monday-Wednesday this week. I'm making an exception for Sasha's defence as there are hard deadlines involved.

**Comment by samm82** [comment]
Not a problem; enjoy your break!
