### ISSUE TITLE
Should I "double count" discrepancies "standalone" synonym discrepancies?

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#85]
_**NOTE:** Once we come to a "consensus" on this, leave this issue open and I'll shift it to an "action-item" issue._

I've been working on automating the counting of discrepancies (as discussed in #83 and #84) and have it mostly done! I'm now just handling some edge cases, and then I'll start generating the pie charts mentioned in #83.

I noticed that there is some overlap between the "standalone" discrepancies (e.g., those focused on specific subsets of test approaches) and the "wider" discrepancies, synonym discrepancies in particular. **Should these be double-counted, or just counted as part of the standalone discrepancies? Does it even make sense to be counting discrepancies within specific subsets of testing, since this ends up in a non-orthogonal classification?** The following quotes are these instances that occur currently:

# Functional Testing
1. Notably, ISO/IEC and IEEE (2017) lists both as synonyms of “black-box testing” (pp. 431, 196, respectively), despite them sometimes being defined separately. For example, the International Software Testing Qualifications Board (ISTQB) defines “specification-based testing” as “testing based on an analysis of the specification of the component or system” (and gives “black-box testing” as a synonym) and “functional testing” as “testing performed to evaluate if a component or system satisfies functional requirements” (specifying no synonyms) (Hamburg and Mogyorodi, 2024)…
2. A complicating factor is that “compliance testing” is also (plausibly) given as a synonym of “conformance testing” (Kam, 2008, p. 43). However, “conformance testing” can also be defined as testing that evaluates the degree to which “results … fall within the limits that define acceptable variation for a quality requirement” (ISO/IEC and IEEE, 2017, p. 93), which seems to describe something different.
3. “Functionality” is defined as the “capabilities of the various … features provided by a product” (ISO/IEC and IEEE, 2017, p. 196) and is said to be a synonym of “functional suitability” (Hamburg and Mogyorodi, 2024), although it seems like it should really be a synonym of “functional completeness” based on (ISO/IEC, 2023a), which would make “functional suitability” a sub-approach. 
4. A distinction is sometimes made (Firesmith, 2015, p. 30) but without accompanying definitions, it is hard to evaluate its merit. Since this terminology is not standardized, I propose[^1] that the two terms are treated as synonyms (as done by other sources (LambdaTest, 2024; Bocchino and Hamilton, 1996))…

# Scalability Testing
1. ISO/IEC and IEEE give “scalability testing” as a synonym of “capacity testing” (2021, p. 39) while other sources differentiate between the two (Firesmith, 2015, p. 53; Bas, 2024, pp. 22-23)

[^1]: I realize that my own analysis/recommendation peeks in here; this will be tackled later.

**Comment by JacquesCarette** [comment]
I feel like I'm missing some background to understand prelude (i.e. the two paragraphs at the top after the note). I don't think I understand your discrepancy classification well enough to have an opinion.

The details on 'functional testing' seem like they need discussion - there seems to be subtleties that need some expansion.

**Comment by samm82** [comment]
I think this discussion would make more sense to have synchronously during our meeting on Monday so that we can all get on the same page and make sure that I'm communicating everything clearly (which is quite important given the topic of my research 😅).

**Comment by samm82** [comment]
Resolved as of #86 and follow up commits
