### ISSUE TITLE
Thesis Meeting | Aug 27, 2024 - ~4pm - Teams

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#86]
# Logistics
_We don't need to discuss this section during the meeting unless anything needs clarification/correction_

My lease ends at the end of August, so I have moved back with my parents while I finish my Master's (and SortingHat!); this will also give me more support while I figure out my mental health. 🥰 Some implications of this:
- I'll be virtual for most meetings; if there is something that I should be in person for (including seminars/my actual defense) I can drive down for the day. This includes this type of meeting, and/or any wider Drasil meetings; just let me know and I'll do my best!
- I've taken the textbooks I've borrowed from you with me (there are still some areas I want to double-check). I haven't forgotten about them and will return them closer to the end of this journey! 😁
- I borrowed a monitor for use in my office, which I think gets returned to the storage room. I wasn't sure if it was locked, so I've packed it up and it is sitting on my office desk. We can coordinate returning it when I'm back in Hamilton, or someone can just deal with it on my behalf (maybe @balacij would be willing/able?)

# Agenda
1. Clarification on counting discrepancies
   1. Review/discussion of my pie charts (0e432ed) - do these make sense?
   2. #85
2. _(Optional)_ Any areas that stand out to start/continue to analyze from my graphs?

**Comment by JacquesCarette** [comment]
It would probably make sense to have our next meeting be in person (sorry). But it can't be Monday mornings, starting next week, as I have committed those to something else. Tuesday would be optimal for me next week.

**Comment by samm82** [comment]
@smiths Would you be joining us on Tuesday or are you still on vacation? Tuesday afternoon would be best for me; is there a specific time you'd want @JacquesCarette?

**Comment by smiths** [comment]
@samm82 I'm off for this week.

**Comment by samm82** [comment]
@JacquesCarette I think 4:30 would be ideal for me, since I have another meeting off campus at a yet-unknown time. That way, if our Drasil meeting goes a bit long and I'm stuck off-campus for it, I'd still have enough time to get to campus for this! Would that work for you?

**Comment by balacij** [comment]
> I borrowed a monitor for use in my office, which I think gets returned to the storage room. I wasn't sure if it was locked, so I've packed it up and it is sitting on my office desk. We can coordinate returning it when I'm back in Hamilton, or someone can just deal with it on my behalf (maybe @balacij would be willing/able?)

I can help out, yep. I'll just need the who/what details :)

**Comment by JacquesCarette** [comment]
Is it too late to move this to another day? I was thinking that the next meeting with all 3 of us would be in-person, and I had forgotten that Dr. Smith was off this week. So I was thinking we'd either make this one still virtual or move it to Thursday?

**Comment by samm82** [comment]
Out of those two options, I'd prefer moving it to virtual, unless you'd prefer in-person. If 4:30 tomorrow doesn't work for you, I could also be virtual earlier in the day (i.e., any time); otherwise, I can be in-person Thursday afternoon.

**Comment by JacquesCarette** [comment]
I can definitely do virtual tomorrow, pretty much any time works for me as well.

**Comment by samm82** [comment]
Unless you have another preference, let's do after our Drasil meeting

**Comment by samm82** [comment]
I made some changes to counting discrepancies (including what terminology I use) - something that Dr. Carette mentioned is that common vocabulary can lead to confusion/ambiguity, so sometimes it is better to introduce _new_ terminology free from preconceived notions; the rest of discussion will be moved to the new meeting agenda
