### ISSUE TITLE
Meeting time going forwards?

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#87]
Unless there's something I'm missing, it doesn't look like there's much overlap in availability for September 😅 It looks like Wed. and Fri. are the best days to schedule meetings. If we are hoping for in-person meetings (which I am), I would prefer Friday, in which case it looks like 9:30-10:30am and 11:30-12:30 are the best time slots (I would prefer the latter). I could also make Wednesday work, in which case 9:30-11am looks like the best slot. (I'm assuming that @JacquesCarette wouldn't necessarily like to meet just before or just after 706, which appear to be the only times that work for @smiths 😩) Thoughts?

I still haven't gotten around to following up on #86, but once I do and have a better idea of where I am, I'll make an issue for our next meeting! 😁

Related: are we still having Drasil meetings going forward?

**Comment by smiths** [comment]
@samm82 I can make any of the times you listed work.  We probably don't want to start the meeting at 9:30 am though, since it is typically easier for @JacquesCarette to have a later start time.

**Comment by samm82** [comment]
Unless we'd want to coordinate when @balacij's thesis meetings would be happening (assuming they still are) or it interferes with people's lunch plans, I'm OK to "lock in" Fridays at noon-12:30. Would that work for you @JacquesCarette?

**Comment by JacquesCarette** [comment]
Looking at the schedules again, it looks like Tuesdays at 2:30pm works. I'd much prefer that over Friday.

**Comment by samm82** [comment]
Sorry for the late reply, but I confirmed that this works for me. Unless @smiths has any issues with that, I'll see you both in person tomorrow! 🥳 (and will try to make an agenda in the morning beforehand 😅)

**Comment by smiths** [comment]
Sounds good @samm82.
