### ISSUE TITLE
Thesis Meeting | Sep 3, 2024 - 2:30pm - ITB 167

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#88]
# Agenda
1. Revisiting counting discrepancies
   1. Changes from #86, in particular getting Dr. Smith's feedback
   2. How can discrepancy types be more "formalized"?
      - Discrepancies between approaches vs. between supp. terms, such as synonyms (see "Although this is…" footnote) or definitions (suggested below)
      - Some ideas I had for discrepancy categories: definitions (of approaches and/or supp. terms), names (including acronyms), typos and/or redundancies (we could just call this "minor" and define what we mean by this)
         - "Definitions" may then be decomposed into those that are incorrect, missing, inconsistent, ambiguous, or that overlap
2. Thesis next steps (i.e., things to focus on _instead of_ more research! 😢)
   1. Research question(s); my ~~current~~ outdated ones from my committee meeting are:
      1. What information is necessary for different types of testing?
      2. How can test cases be generated from information that currently exists within Drasil?
      3. How can new information be added to facilitate the generation of more types of testing?
   2. Conclusions
      1. Note if property-based testing is never reached (potentially in introduction)
      2. Future work

**Comment by samm82** [comment]
We mainly talked about 1i and 2 in general, focusing on our timeline. We suggested the category title of "papers+" when discussing "other documents" for clarity; I'll introduce that in a future change.

To be perfectly honest, there's still some things I want to wrap up/investigate in terms of actual research just for my own expectations/desires for my Master's; I'd much rather do it well than do it quickly (although both is obviously ideal!) - being realistic (especially in light of what a Sept-based timeline would look like 😬😅) and considering these "final" action items on my end, I could see my thesis going into October, which would definitely be OK with me, unless there are any objections. Would reaching out to my committee to start investigating seminar times in October be alright? @smiths @JacquesCarette 

Everything else, if still relevant, will be addressed next meeting.

**Comment by JacquesCarette** [comment]
Fine with me.

**Comment by smiths** [comment]
Yes, this is fine with me too.  I like your emphasis on quality @samm82.  A small extension into October will also have a dramatic decrease on your stress levels.  :smile:

**Comment by samm82** [comment]
Between #89 and #90, this issue can be closed.
