### ISSUE TITLE
Investigating Source Categorizations

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#89]
I _finally_ got around to analyzing what sources I use in my glossaries and what categories they should be to investigate the "papers+" category mentioned in #88. Currently, this is the breakdown:

![image](https://github.com/user-attachments/assets/9704dd55-f810-41be-91b7-e80bebf3baf1)

Upon analysis, most of these entries are papers, but based on some quirks, I'm thinking of making the following changes:
1. Two sources are textbooks, so I think it makes more sense to have a more general "textbooks" category, instead of arbitrarily limiting it to textbooks trusted at McMaster (I'll then tweak the note about our original starting point to mention these specific sources instead of the whole category).
2. One paper is a literature review, which I think makes more sense as a "meta" source, rather than an "other source"
3. Three papers are reports and one is a thesis, which may have less weight than traditional papers. I could see the argument for these being considered "papers", or "less academic sources" (along with the two websites and the booklet also referenced).
4. The original proposition for "papers+" was mainly done to keep the number of categories nice for displaying on my pie charts page (i.e., introducing a fifth would result in an odd number). However, it has been on my mind for a bit to also distinguish between inferred relations (i.e., a relation that follows trivially from names or definitions, including those I note may be the case but don't have an explicit source). We've previously mentioned keeping inferred discrepancies separate (#84), so I think doing the same visually with our graphs also makes sense. Currently, the "other" category is used as a catch-all, but there is definitely a distinction between "a source not in a previous category" and "no source". Introducing this as well would bring us up to six pie charts (turning "other" → "papers" and introducing "less academic sources" and "inference").

Thoughts? Of course, feel free to ask follow-up questions to this if anything isn't clear. 😅

**Comment by smiths** [comment]
Yes, changing the category to textbooks is better than "trusted textbooks".  I forgot what the trusted textbooks category meant.  Books we have on our shelves can be a good starting point, but it isn't the best basis for a methodology.  :smile:

Yes, a literature review makes sense as a meta source.

You will have full traceability to all of these decision correct?  I'm sure you will, but it is worth emphasizing that we want complete transparency.  Another scholar should be able to look at all of our decisions.  With your tools support it will likely also be easy to change decisions and see the ramifications of that change.

Categorizing reports and theses as papers+ seems fine to me. 

Yes, if I understand correctly, you should be explicit about "no source" when that is the case.

Breaking up Other sources makes sense.  It currently dominates the pie chart, so anyone looking at it is going to ask the question, what does Other refer to.  Usually a catchall category is used to represent the fewest entries in a category, not the most.

**Comment by samm82** [comment]
> Categorizing reports and theses as papers+ seems fine to me.

Would it be sufficient to label this category as "Papers"? I'm currently refactoring how these [`sources`](https://github.com/samm82/TestGen-Thesis/tree/sources) are explained to make them more consistent/explicit, so there would be an explanation to what this all entails (i.e., that it includes reports, theses, journal articles, conference papers, etc.). This would also improve the traceability, including for these decisions!

**Comment by smiths** [comment]
Yes, the category name of "Papers" is sufficiently generic to cover all the academic sources you've mentioned.
