### ISSUE TITLE
Dr. Smith's Review of Introduction (and Scope?)

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#96]
**Links**: [thesis](https://github.com/samm82/TestGen-Thesis/blob/main/thesis.pdf) and [paper](https://github.com/samm82/TestGen-Thesis/blob/main/paper.pdf)
**Introduction**: Chapter 1 of thesis and Section I of paper
**Scope**: Chapter 2 of thesis and Section II of paper

I've went through and made some improvements to the introduction of my thesis (see #95, #92). Looking into various online resources for writing intros (to theses _and_ papers), I can really only find generic advice that I've already been following: start broad, focus in on your target area, make the reader care, justify the problem, introduce your research questions, etc. I'm not sure how long an introduction should be, especially given that it makes the most sense to write it _last_, since then you will have a more in-depth picture of the overall "story" of the thesis.

Regardless, I _think_ the introduction is in a spot where a review would be beneficial, at least to determine how much effort to focus on it further and in which specific areas. Since it is a smaller and more trivial section, I did some overhauling of the Scope section that spawned from my work on the intro, so I think a similar review of what needs more work would be helpful. I'll leave it up to your judgement to review this, or wait until I've had a chance to respond to the Intro feedback (which also might suggest improvements to the Scope section).

**Comment by smiths** [comment]
@samm82 here is a review of your first two chapters.  The work you have done is great, but we'll need to work on presenting it.  You can read the details, but the two biggest items of feedback are:

1. The intro needs an high-level overview of what you did.  You presented the problem in the intro and your contribution, but you missed the middle part.  You have the why and the what, but you are missing the how.  :smile:
2. In the scope section you rely on the examples to let the reader deduce your scope. The examples are good, but you should have clear explicit statements that define the scope.

[SamCrawford_thesis.pdf](https://github.com/user-attachments/files/17284750/SamCrawford_thesis.pdf)
